services:
  app:
    build: .
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    # Exécuter en tant qu'utilisateur courant pour éviter les problèmes de droits
    user: "1000:1000" 

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fsp_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin
    container_name: fullservicepoint-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - laravel-network      

networks:
  laravel-network:
    driver: bridge